/* eslint-disable */
/**
* This file was automatically generated by json-schema-to-typescript.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run json-schema-to-typescript to regenerate this file.
*/

export type Inputpath = string
export type Outputpath = string
export type Starttime = number
export type Endtime = (number | null)
export type RootModelStr = string
export type Inputpath1 = string
export type Duration = number
export type Fps = number
/**
 * @minItems 2
 * @maxItems 2
 */
export type Size = [unknown, unknown]
export type Audio = boolean
export type Inputpath2 = string
export type Starttime1 = number
export type Endtime1 = (number | null)

/**
 * Commands Input and Output Schemas
 */
export interface Commands {
clip_video: {
input: VideoClipRequest
output: RootModelStr
}
get_video_info: {
input: VideoInfoRequest
output: VideoInfoResponse
}
generate_preview: {
input: PreviewRequest
output: RootModelStr
}
}
/**
 * Request to clip a video segment.
 * 
 * @property inputPath - Path to the input video file.
 * @property outputPath - Path where the clipped video will be saved.
 * @property startTime - Start time in seconds.
 * @property endTime - End time in seconds (optional, defaults to video duration).
 */
export interface VideoClipRequest {
inputPath: Inputpath
outputPath: Outputpath
startTime?: Starttime
endTime?: Endtime
}
/**
 * Request to get video information.
 * 
 * @property inputPath - Path to the video file.
 */
export interface VideoInfoRequest {
inputPath: Inputpath1
}
/**
 * Video information response.
 * 
 * @property duration - Video duration in seconds.
 * @property fps - Frames per second.
 * @property size - Video resolution as [width, height].
 * @property audio - Whether the video has audio track.
 */
export interface VideoInfoResponse {
duration: Duration
fps: Fps
size: Size
audio: Audio
}
/**
 * Request to generate video preview.
 * 
 * @property inputPath - Path to the input video file.
 * @property startTime - Start time in seconds.
 * @property endTime - End time in seconds (optional, defaults to video duration).
 */
export interface PreviewRequest {
inputPath: Inputpath2
startTime?: Starttime1
endTime?: Endtime1
}
