/* eslint-disable */
/**
 * This file was automatically generated by pytauri-gen-ts.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source commands API,
 * and run pytauri-gen-ts to regenerate this file.
 */

import { pyInvoke } from "tauri-plugin-pytauri-api";
import type { InvokeOptions } from "@tauri-apps/api/core";

import type { Commands } from "./_apiTypes.d.ts";

/**
 * Clip a video segment.
 *
 * @param body - The video clip request parameters.
 */
export async function clipVideo(
    body: Commands["clip_video"]["input"],
    options?: InvokeOptions
): Promise<Commands["clip_video"]["output"]> {
    return await pyInvoke("clip_video", body, options);
}

/**
 * Get information about a video file.
 *
 * @param body - The video info request parameters.
 */
export async function getVideoInfo(
    body: Commands["get_video_info"]["input"],
    options?: InvokeOptions
): Promise<Commands["get_video_info"]["output"]> {
    return await pyInvoke("get_video_info", body, options);
}

/**
 * Generate a preview video clip with lower quality for faster processing.
 *
 * @param body - The preview request parameters.
 */
export async function generatePreview(
    body: Commands["generate_preview"]["input"],
    options?: InvokeOptions
): Promise<Commands["generate_preview"]["output"]> {
    return await pyInvoke("generate_preview", body, options);
}
